-- 1) Use a powerful role (trial usually has ACCOUNTADMIN)
USE ROLE ACCOUNTADMIN;

-- 2) Warehouses (small + auto-suspend to save credits)
CREATE OR REPLACE WAREHOUSE WH_ETL
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE WAREHOUSE WH_BI
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 3) Database + schemas
CREATE OR REPLACE DATABASE OLIST_DW;

CREATE OR REPLACE SCHEMA OLIST_DW.RAW;
CREATE OR REPLACE SCHEMA OLIST_DW.STG;
CREATE OR REPLACE SCHEMA OLIST_DW.MART;
CREATE OR REPLACE SCHEMA OLIST_DW.UTIL;

-- 4) File format (CSV)
CREATE OR REPLACE FILE FORMAT OLIST_DW.UTIL.CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- 5) Internal stage (where I will upload CSV files)
CREATE OR REPLACE STAGE OLIST_DW.UTIL.RAW_STAGE
  FILE_FORMAT = OLIST_DW.UTIL.CSV_FF;
