USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_ETL;
USE DATABASE OLIST_DW;

COPY INTO RAW.CUSTOMERS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_customers_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.ORDERS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_orders_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.ORDER_ITEMS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_order_items_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.ORDER_PAYMENTS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_order_payments_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.ORDER_REVIEWS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_order_reviews_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.PRODUCTS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_products_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.SELLERS
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_sellers_dataset.csv
ON_ERROR='ABORT_STATEMENT';

COPY INTO RAW.CATEGORY_TRANSLATION
FROM @OLIST_DW.UTIL.RAW_STAGE/product_category_name_translation.csv
ON_ERROR='ABORT_STATEMENT';

-- Optional (you have it uploaded, so load it)
COPY INTO RAW.GEOLOCATION
FROM @OLIST_DW.UTIL.RAW_STAGE/olist_geolocation_dataset.csv
ON_ERROR='CONTINUE';


SELECT 'customers' t, COUNT(*) c FROM RAW.CUSTOMERS
UNION ALL SELECT 'orders', COUNT(*) FROM RAW.ORDERS
UNION ALL SELECT 'order_items', COUNT(*) FROM RAW.ORDER_ITEMS
UNION ALL SELECT 'payments', COUNT(*) FROM RAW.ORDER_PAYMENTS
UNION ALL SELECT 'reviews', COUNT(*) FROM RAW.ORDER_REVIEWS
UNION ALL SELECT 'products', COUNT(*) FROM RAW.PRODUCTS
UNION ALL SELECT 'sellers', COUNT(*) FROM RAW.SELLERS
UNION ALL SELECT 'translation', COUNT(*) FROM RAW.CATEGORY_TRANSLATION
UNION ALL SELECT 'geolocation', COUNT(*) FROM RAW.GEOLOCATION;
