USE ROLE ACCOUNTADMIN;

ALTER WAREHOUSE WH_ETL SET
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  WAREHOUSE_SIZE = 'XSMALL';

ALTER WAREHOUSE WH_BI SET
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  WAREHOUSE_SIZE = 'XSMALL';

CREATE OR REPLACE RESOURCE MONITOR RM_OLIST
  WITH CREDIT_QUOTA = 5
  FREQUENCY = DAILY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE WH_ETL SET RESOURCE_MONITOR = RM_OLIST;
ALTER WAREHOUSE WH_BI  SET RESOURCE_MONITOR = RM_OLIST;

SHOW RESOURCE MONITORS;
SHOW WAREHOUSES LIKE 'WH_%';
