USE ROLE ACCOUNTADMIN;

-- (A) Create DEV database as a zero-copy clone of PROD
CREATE OR REPLACE DATABASE OLIST_DW_DEV CLONE OLIST_DW;

-- (B) Prove it exists
SHOW DATABASES LIKE 'OLIST_DW%';

-- (C) UNDROP demo 
DROP TABLE OLIST_DW_DEV.MART.FCT_ORDER_ITEMS;

-- Recover it
UNDROP TABLE OLIST_DW_DEV.MART.FCT_ORDER_ITEMS;

-- Verify table is back
SELECT COUNT(*) AS rows_after_undrop
FROM OLIST_DW_DEV.MART.FCT_ORDER_ITEMS;

SELECT COUNT(*) AS prod_orders FROM OLIST_DW.MART.FCT_ORDERS;
SELECT COUNT(*) AS prod_items  FROM OLIST_DW.MART.FCT_ORDER_ITEMS;
